Update Centos7

diff --git a/Centos7 b/Centos7
--- a/Centos7
+++ b/Centos7
@@ -3,7 +3,7 @@
 
 #Requirement
 if [ ! -e /usr/bin/curl ]; then
-   #yum -y update && yum -y upgrade
+   yum -y update && yum -y upgrade
    yum -y install curl
 fi
 
@@ -15,12 +15,52 @@ if [ $MYIP = "" ]; then
 fi
 MYIP2="s/xxxxxxxxx/$MYIP/g";
 
+# Setting Terminal Message
+[[ `cat .profile` =~ Dexter ]] ||
+cat << 'intro' >> .profile
+clear
+echo -e '
+    |$$$$$$$$$$$$| |$$$$$$$$$$$$|
+         |$$|           |$$|
+         |$$|           |$$|
+         |$$|           |$$|
+         |$$|           |$$|
+         |$$|           |$$|
+         |$$|       |$$$$$$|
+         |__|       \______/  
+' && echo "
+========================================
+=++++++++ Welcome To TsholoVPN ++++++++=
+"
+intro
+
 # go to root
 cd
+echo -e " Choose VPN Server installation type:"
+echo -e " [1] Premium Server"
+echo -e " [2] VIP Server"
+echo -e " [3] Private Server"
+until [[ "$opts" =~ ^[1-3]$ ]]; do
+read -rp " Choose from [1-3]: " -e opts
+done
+
+case $opts in
+	1)
+		CATEGORY="user.is_duration > 0"
+		;;
+	2)
+		CATEGORY="user.vip_duration > 0"
+		;;
+   3)
+		CATEGORY="user.private_duration > 0"
+		;;
+	esac
 
 # Mysql Database Info
-DatabasePass='s+(WT#r4CaB&'
-DatabaseName='vpnquest1_dbase'
+$DatabaseHost = '185.61.137.174';
+$DatabaseUser = 'vpnquest1_user';
+$DatabasePass = 's+(WT#r4CaB&';
+$DatabaseName = 'vpnquest1_dbase';
 
 # disable se linux
 echo 0 > /selinux/enforce
@@ -82,13 +122,260 @@ chmod +x /usr/bin/screenfetch
 echo "clear" >> .bash_profile
 echo "screenfetch" >> .bash_profile
 
-# install openvpn
+# [ Setup Openvpn ]
+# OpenVPN Cert CA
+mkdir /etc/openvpn/easy-rsa
+cat << CA > /etc/openvpn/easy-rsa/ca.crt
+-----BEGIN CERTIFICATE-----
+MIIEbjCCA1agAwIBAgIJAJdSDmspwxUnMA0GCSqGSIb3DQEBCwUAMIGAMQswCQYD
+VQQGEwJaQTELMAkGA1UECBMCR1QxFDASBgNVBAcTC1ZlcmVlbmlnaW5nMRIwEAYD
+VQQKEwlUc2hvbG9WUE4xFTATBgNVBAMTDFRzaG9sb1ZQTiBDQTEjMCEGCSqGSIb3
+DQEJARYUYWRtaW5AdHNob2xvdnBuLmluZm8wHhcNMTUwODI0MTA1NDE3WhcNMjUw
+ODIxMTA1NDE3WjCBgDELMAkGA1UEBhMCWkExCzAJBgNVBAgTAkdUMRQwEgYDVQQH
+EwtWZXJlZW5pZ2luZzESMBAGA1UEChMJVHNob2xvVlBOMRUwEwYDVQQDEwxUc2hv
+bG9WUE4gQ0ExIzAhBgkqhkiG9w0BCQEWFGFkbWluQHRzaG9sb3Zwbi5pbmZvMIIB
+IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4dKR9lbZIVmANbQORRd/lV9+
+qfvGE3z7pkNjdvBh8baVpOImn3+6rANbgUPNisnXvGGx+0rLfZdB/MEqDp21wiwf
+ytoy2E5ZmJHB8Xp58PR1SNxCHz5q1qM7WlJ0GHYY+0I45OF9sz9sBNnJBXstpi8T
+T2jfsjyCpZ6RRuT363yapZ+sayuay3U7T3tQw5Qmca7DUVXGjaEHitQiA4U5rfHd
+LNifhxkZY3hERdRIlsgPZHQIZY5rn8O3BMqcHPeTMLnCnZyOc468NPoeXdc/WwAc
+SaxhApszlwk/ILwjLpnY2aDSBIn5Kd1zTfZyR6yc6MIcYysMhkLczDub+2rHGQID
+AQABo4HoMIHlMB0GA1UdDgQWBBQiIe8AGlmSBwE0ikGPz0UWGurzuDCBtQYDVR0j
+BIGtMIGqgBQiIe8AGlmSBwE0ikGPz0UWGurzuKGBhqSBgzCBgDELMAkGA1UEBhMC
+WkExCzAJBgNVBAgTAkdUMRQwEgYDVQQHEwtWZXJlZW5pZ2luZzESMBAGA1UEChMJ
+VHNob2xvVlBOMRUwEwYDVQQDEwxUc2hvbG9WUE4gQ0ExIzAhBgkqhkiG9w0BCQEW
+FGFkbWluQHRzaG9sb3Zwbi5pbmZvggkAl1IOaynDFScwDAYDVR0TBAUwAwEB/zAN
+BgkqhkiG9w0BAQsFAAOCAQEAwPP8Omorca2f5uzYrnROmqOEtlwaJb/t8WbeBVd0
+HzeXQRyhn5ssx1ZPZCYP3GwsQU/0xPrs/wwIVpAimK66qdTNoii4qYFcJ0u18Nnh
+BtgS6r7Lgyl0X+u2aSj6mYjqNySkKnXBgsaD6/Z35P/2PK7b/xN7K2eShadj+5Ry
+7AXIVZIqN32ha3Ugs8FAc3EDfaBgeLBUm+hznxNu059PG1T6jTCbLAfDBbbhMrN1
+zC8w5j+UXyV3qCP64s2HNP5ZU/aoSnK/QYFUgLxq+RccR/Ph6bctNu81uwta10lc
+Q7A78Dl5voYKxdoitmPZIrE41q9cuRmbS22rhcaNYLL+iA==
+-----END CERTIFICATE-----
+CA
+
+# Server CRT
+cat << CRT > /etc/openvpn/easy-rsa/TsholoVPN.crt
+Certificate:
+    Data:
+        Version: 3 (0x2)
+        Serial Number: 1 (0x1)
+    Signature Algorithm: sha256WithRSAEncryption
+        Issuer: C=ZA, ST=GT, L=Vereeniging, O=TsholoVPN, CN=TsholoVPN CA/emailAddress=admin@tsholovpn.info
+        Validity
+            Not Before: Aug 24 10:54:37 2015 GMT
+            Not After : Aug 21 10:54:37 2025 GMT
+        Subject: C=ZA, ST=GT, L=Vereeniging, O=TsholoVPN, CN=TsholoVPN/emailAddress=admin@tsholovpn.info
+        Subject Public Key Info:
+            Public Key Algorithm: rsaEncryption
+                Public-Key: (2048 bit)
+                Modulus:
+                    00:b5:f0:64:f7:de:02:fb:35:00:53:95:34:97:cb:
+                    8b:c1:f6:7b:7c:89:5a:7d:09:05:6f:e8:ee:f3:3e:
+                    e8:08:89:23:76:97:e9:ea:05:1e:2d:cc:82:0e:97:
+                    99:2d:f1:64:ab:d0:25:c6:06:fc:b2:6b:3e:5b:24:
+                    d1:26:3e:b5:e9:48:81:f4:b9:6a:4b:b9:28:28:ef:
+                    76:78:c0:f7:ff:7e:f7:44:44:18:46:64:fb:31:f2:
+                    b8:ba:fe:2e:05:95:cd:26:fe:19:9f:5f:01:a0:7c:
+                    3e:76:84:50:a0:0a:a1:07:db:1a:2b:d5:42:cc:2b:
+                    2c:14:8c:6b:04:76:2a:d3:46:56:60:93:14:14:46:
+                    06:69:8a:93:46:2b:76:69:a0:79:46:ca:e7:25:48:
+                    12:55:76:9b:e4:8c:69:4b:50:72:eb:2a:52:d0:5e:
+                    ae:84:0a:3c:29:88:81:3c:f8:ae:5b:e4:f3:c4:83:
+                    8d:67:bb:94:5a:37:f9:b4:45:09:d2:95:9b:97:3a:
+                    bc:b7:3d:48:8a:f4:98:68:5d:0c:aa:01:22:60:05:
+                    de:7c:eb:78:85:fd:eb:9b:c0:d8:7f:b0:c4:98:a7:
+                    b5:02:c9:d4:17:5a:5f:ac:87:8c:d3:8d:f2:22:c3:
+                    b0:93:29:45:66:72:85:2d:6d:45:07:ce:32:0d:61:
+                    11:d7
+                Exponent: 65537 (0x10001)
+        X509v3 extensions:
+            X509v3 Basic Constraints: 
+                CA:FALSE
+            Netscape Cert Type: 
+                SSL Server
+            Netscape Comment: 
+                Easy-RSA Generated Server Certificate
+            X509v3 Subject Key Identifier: 
+                F9:A1:AE:4A:9E:02:9D:9B:0A:C6:82:AF:4C:B8:99:1C:EE:FD:E4:F5
+            X509v3 Authority Key Identifier: 
+                keyid:22:21:EF:00:1A:59:92:07:01:34:8A:41:8F:CF:45:16:1A:EA:F3:B8
+                DirName:/C=ZA/ST=GT/L=Vereeniging/O=TsholoVPN/CN=TsholoVPN CA/emailAddress=admin@tsholovpn.info
+                serial:97:52:0E:6B:29:C3:15:27
+
+            X509v3 Extended Key Usage: 
+                TLS Web Server Authentication
+            X509v3 Key Usage: 
+                Digital Signature, Key Encipherment
+    Signature Algorithm: sha256WithRSAEncryption
+         59:40:cd:31:c1:54:92:39:94:22:d3:cc:f5:3f:c3:6e:63:31:
+         a2:d7:ad:1a:fa:7f:dc:b2:66:c1:86:a4:51:95:ae:4a:03:f2:
+         80:dc:06:af:9e:bf:5a:6b:5c:8c:9e:99:2d:b1:87:57:2c:ac:
+         29:61:fd:90:6d:e3:cd:9a:3c:62:d5:1c:8a:13:87:5b:73:ed:
+         57:cf:fc:a1:a7:13:77:30:c2:28:92:88:ba:71:2c:e4:db:e8:
+         d7:8b:10:6c:74:a0:93:30:71:02:03:18:f3:d3:5f:ed:72:4b:
+         10:52:30:36:4e:24:5e:d3:52:14:0d:27:12:74:a3:1e:fe:c0:
+         25:8e:fa:32:66:61:f5:1f:02:db:c3:76:4b:66:01:d3:98:9d:
+         6a:50:5b:38:e8:6a:3e:1a:64:cf:56:b6:7f:5b:af:29:8f:e4:
+         7c:9c:f6:b2:6f:4e:8e:de:28:13:8f:0b:04:16:d1:9f:fc:4c:
+         69:c4:2a:21:69:79:21:52:1a:66:93:9d:ea:a1:e6:0e:09:4c:
+         ae:49:eb:8e:6b:e9:48:bd:04:8b:97:c1:f1:5d:7f:02:da:c1:
+         fb:f3:cc:17:8d:2d:49:63:55:9f:39:33:a4:66:3c:73:1f:a9:
+         56:8d:68:52:2c:9e:1c:c0:47:dc:85:03:48:7f:c2:3f:fb:e2:
+         a2:da:bc:71
+-----BEGIN CERTIFICATE-----
+MIIEzDCCA7SgAwIBAgIBATANBgkqhkiG9w0BAQsFADCBgDELMAkGA1UEBhMCWkEx
+CzAJBgNVBAgTAkdUMRQwEgYDVQQHEwtWZXJlZW5pZ2luZzESMBAGA1UEChMJVHNo
+b2xvVlBOMRUwEwYDVQQDEwxUc2hvbG9WUE4gQ0ExIzAhBgkqhkiG9w0BCQEWFGFk
+bWluQHRzaG9sb3Zwbi5pbmZvMB4XDTE1MDgyNDEwNTQzN1oXDTI1MDgyMTEwNTQz
+N1owfTELMAkGA1UEBhMCWkExCzAJBgNVBAgTAkdUMRQwEgYDVQQHEwtWZXJlZW5p
+Z2luZzESMBAGA1UEChMJVHNob2xvVlBOMRIwEAYDVQQDEwlUc2hvbG9WUE4xIzAh
+BgkqhkiG9w0BCQEWFGFkbWluQHRzaG9sb3Zwbi5pbmZvMIIBIjANBgkqhkiG9w0B
+AQEFAAOCAQ8AMIIBCgKCAQEAtfBk994C+zUAU5U0l8uLwfZ7fIlafQkFb+ju8z7o
+CIkjdpfp6gUeLcyCDpeZLfFkq9Alxgb8sms+WyTRJj616UiB9LlqS7koKO92eMD3
+/373REQYRmT7MfK4uv4uBZXNJv4Zn18BoHw+doRQoAqhB9saK9VCzCssFIxrBHYq
+00ZWYJMUFEYGaYqTRit2aaB5RsrnJUgSVXab5IxpS1By6ypS0F6uhAo8KYiBPPiu
+W+TzxIONZ7uUWjf5tEUJ0pWblzq8tz1IivSYaF0MqgEiYAXefOt4hf3rm8DYf7DE
+mKe1AsnUF1pfrIeM043yIsOwkylFZnKFLW1FB84yDWER1wIDAQABo4IBUTCCAU0w
+CQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBkAwNAYJYIZIAYb4QgENBCcWJUVh
+c3ktUlNBIEdlbmVyYXRlZCBTZXJ2ZXIgQ2VydGlmaWNhdGUwHQYDVR0OBBYEFPmh
+rkqeAp2bCsaCr0y4mRzu/eT1MIG1BgNVHSMEga0wgaqAFCIh7wAaWZIHATSKQY/P
+RRYa6vO4oYGGpIGDMIGAMQswCQYDVQQGEwJaQTELMAkGA1UECBMCR1QxFDASBgNV
+BAcTC1ZlcmVlbmlnaW5nMRIwEAYDVQQKEwlUc2hvbG9WUE4xFTATBgNVBAMTDFRz
+aG9sb1ZQTiBDQTEjMCEGCSqGSIb3DQEJARYUYWRtaW5AdHNob2xvdnBuLmluZm+C
+CQCXUg5rKcMVJzATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMCBaAwDQYJ
+KoZIhvcNAQELBQADggEBAFlAzTHBVJI5lCLTzPU/w25jMaLXrRr6f9yyZsGGpFGV
+rkoD8oDcBq+ev1prXIyemS2xh1csrClh/ZBt482aPGLVHIoTh1tz7VfP/KGnE3cw
+wiiSiLpxLOTb6NeLEGx0oJMwcQIDGPPTX+1ySxBSMDZOJF7TUhQNJxJ0ox7+wCWO
++jJmYfUfAtvDdktmAdOYnWpQWzjoaj4aZM9Wtn9brymP5Hyc9rJvTo7eKBOPCwQW
+0Z/8TGnEKiFpeSFSGmaTneqh5g4JTK5J645r6Ui9BIuXwfFdfwLawfvzzBeNLUlj
+VZ85M6RmPHMfqVaNaFIsnhzAR9yFA0h/wj/74qLavHE=
+-----END CERTIFICATE-----
+CRT
+
+# Server KEY
+cat << KEY > /etc/openvpn/easy-rsa/TsholoVPN.key
+-----BEGIN PRIVATE KEY-----
+MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC18GT33gL7NQBT
+lTSXy4vB9nt8iVp9CQVv6O7zPugIiSN2l+nqBR4tzIIOl5kt8WSr0CXGBvyyaz5b
+JNEmPrXpSIH0uWpLuSgo73Z4wPf/fvdERBhGZPsx8ri6/i4Flc0m/hmfXwGgfD52
+hFCgCqEH2xor1ULMKywUjGsEdirTRlZgkxQURgZpipNGK3ZpoHlGyuclSBJVdpvk
+jGlLUHLrKlLQXq6ECjwpiIE8+K5b5PPEg41nu5RaN/m0RQnSlZuXOry3PUiK9Jho
+XQyqASJgBd5863iF/eubwNh/sMSYp7UCydQXWl+sh4zTjfIiw7CTKUVmcoUtbUUH
+zjINYRHXAgMBAAECggEAZZQX60OqynInAoN1X6KnHt3sx/Uv7ktRG9AjSO/AQLPA
+dwAN+zhsRwm9O0Rso3f4yuxlipBwGXVC1URS+VVd3yc6V1YGAM0ZnPFFZdnnHGDY
+0OZr3zGWBacMeGpda4Tdi32m9JHoqJ91iFoLYa9NhMNRc1OX/cHE1JwpS85lzpqv
+tibPMPa8e6jnvO1wJqc+XpnQmXIpHSQJxK69kRmhuVNrH2Nf9Vqbvuc9AYOObA0m
+88213WfN8pmAgeJNCCiSOCSUFgJHFnM0uswOipLZzWLtbi6jSrLagpIZxKJHdPCE
+nqKJcSiCbGl1eU/rlTmBGDV/nAUxtd0G7Ux6+d6BoQKBgQDYOEW0Y+J6ksFXnTVo
+0axx6YwNqAUuwfIWLafxTBXb8k0AYFVMr9Z6T5hIhXo1jG8041BPTi8GU1JhgA2i
+8x6B8jr1UTuXhHLQqZKB4voLEAzwrCMuftcVE1XS3UGjl6i3sHfmvjBhrfU/NtNZ
+A3mWELxlISRMyLzFZ8Ds1ddHKQKBgQDXaYiRfcbteokChzdO9CgaaN9PylfDMAUn
+E0/cyfaplwg/w/Zpj9fJyejcpvp9y2tCB0Urd6rlWpBwpn2gMtZx8t0v1lpe7IxP
+A7qJ8ozDNqPf21xLsp6faz0UukqprY59YF/yjkgJr5/ZXivAnbxTR9jN9Re4R+3L
+vohSbH2w/wKBgGKi4SGWw3WZRzw5ymij5iAdI7gDI0IeVdrKPyfzxrEMyxXV3HPc
+b2Jitxy2T3boNr8Qx8015HvlPNqfuRjSAePT5hONWDsZv+rywJQiQGEVlGGilXYb
+hPDnXiqQpuYDRINvrHMF5jpZSlzpHOcpj6jmv5r+0Hl6xarkVv1z2/5pAoGBANEw
+r2t7FeAxizRlU5TdDsT260Z1Xd0zmQ1ld70WdPAkt+IU0AuboRdZeUYu8juPfE3W
++ZlI0TGCTZrYVE9qj06BZ8O5CnH8jhV9rX2hiolZWrNeN7dbcyel4N9sOm2lGicv
+nH3VJqghYb6Z8StRAz5tG2KHjc1sLMYb9g71ROrJAoGAGgRaWbx8US8z4hPp/BB8
+6hXvt2QKNNgH/P/oDKcJpqB/Fy2MUO6FnIEQMVSAWj+cZajj8hmKWGFhyuX7NVtt
+EEURauGtar75MsULYhqADzX4ylJYgN+oqPbbJlALEi0+HgoLpyGLNYn38oP/ko8v
+w3VMBwVhspalpBuX2QWNUWE=
+-----END PRIVATE KEY-----
+KEY
+
+# Server DH2048
+ cat << DH > /etc/openvpn/easy-rsa/dh2048.pem
+-----BEGIN DH PARAMETERS-----
+MIIBCAKCAQEA1emiXAI6I7h2niDL+zRZ3CkRs0LTt1jCTL4mPx7O5aT5GjsPzXVb
+GRH6CMlQBE28Uk/Kg1lojfpV2fOL1gmyk7kaRxKO1hmr6fCS07WlfdUUbF2CKK3F
+jRkj6U3NDC0sMgOJI2+io8j2V+xCKNehaz58caozlyo8efwI6cT1jZY2KlEwFbnl
+4D0K7TFJs3K5rhBZ9KOfh10nYVsw0mbWMTwUAlRB/97K9VTnnrDx2WQONIkB/zgt
+5RKpPxmN1d1cJ/7II559PPGiUf/UL4SSXH8L5c05xDLyNoeH6qPbA78umRA3CZEH
+An1jD+OUdrLRqjxcEoel9tm3b9h/YWbu2wIBAg==
+-----END DH PARAMETERS-----
+DH
+
 mkdir -p /dev/net
 mknod /dev/net/tun c 10 200
-wget -O /etc/openvpn/openvpn.zip "https://github.com/tjay13/TsholoVPN/blob/master/Tools/OpenVPN/openvpn.zip?raw=true"
-cd /etc/openvpn/
-unzip openvpn.zip
-chmod -R 755 /etc/openvpn
+mkdir /etc/openvpn/script
+chmod -R 755 /etc/openvpn/script
+mkdir /var/www/html/status
+chmod -R 755 /var/www/html/status
+
+# Creating TCP OpenVPN Config
+cat << TeeJay01 >/etc/openvpn/server.conf
+mode server 
+tls-server 
+port 1194
+proto tcp4 
+dev tun 
+cipher AES-128-CBC
+auth SHA1
+tun-mtu-extra 32 
+tun-mtu 1400 
+mssfix 1360
+tcp-queue-limit 128
+txqueuelen 2000
+tcp-nodelay
+sndbuf 393216
+rcvbuf 393216
+push "sndbuf 393216"
+push "rcvbuf 393216"
+ca /etc/openvpn/easy-rsa/ca.crt
+cert /etc/openvpn/easy-rsa/TsholoVPN.crt
+key /etc/openvpn/easy-rsa/TsholoVPN.key
+dh /etc/openvpn/easy-rsa/dh2048.pem
+script-security 2
+ifconfig-pool-persist ipp.txt
+client-cert-not-required 
+username-as-common-name 
+auth-user-pass-verify "/etc/openvpn/script/auth_vpn.sh" via-file # 
+tmp-dir "/etc/openvpn/" # 
+server 10.200.0.0 255.255.0.0
+push "redirect-gateway def1" 
+push "dhcp-option DNS 8.8.8.8"
+push "dhcp-option DNS 8.8.4.4"
+keepalive 5 30
+persist-key 
+persist-tun
+verb 3 
+status /var/www/html/status/tcp.txt 1
+
+TeeJay01
+
+# Auth Script
+cat <<'TeeJay02' >/etc/openvpn/script/auth_vpn.sh
+#!/bin/bash
+username=`head -n1 $1 | tail -1`   
+password=`head -n2 $1 | tail -1`
+tm="$(date +%s)"
+dt="$(date +'%Y-%m-%d %H:%M:%S')"
+
+HOST='$DatabaseHost'
+USER='$DatabaseUser'
+PASS='$DatabasePass'
+DB='$DatabaseName'
+
+AUTH="user.username='$username' AND user.auth_vpn=md5('$password') AND user.confirmcode='y' AND user.status='live' AND user.is_freeze=1 AND user.is_active=1 AND user.is_ban=1 AND user.is_suspend=1 AND $CATEGORY"
+Query="SELECT user.username FROM user WHERE $AUTH"
+auth_vpn=`mysql -u $USER -p$PASS -D $DB -h $HOST --skip-column-name -e "$Query"`
+  
+if [ "$auth_vpn" == "$username" ]; then
+    echo "user : $username"
+	echo "authentication ok."
+	exit 0
+else
+    echo "authentication failed."
+	exit 1
+fi
+
+TeeJay02
+
+chmod -R 755 /etc/openvpn/script/auth_vpn.sh
+sed -i -e 's/\r$//' /etc/openvpn/script/auth_vpn.sh
+
 wget -O /etc/iptables.up.rules "https://raw.githubusercontent.com/tjay13/TsholoVPN/master/Tools/OpenVPN/iptables.up.rules"
 sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local
 sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.d/rc.local
@@ -220,6 +507,7 @@ COMMIT
 -A POSTROUTING -o eth0 -j MASQUERADE
 -A POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
 -A POSTROUTING -s 10.1.0.0/24 -o eth0 -j MASQUERADE
+-A POSTROUTING -s 10.200.0.0/24 -o eth0 -j MASQUERADE
 COMMIT
 END
 sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local
@@ -251,14 +539,11 @@ ipadd=$(wget -qO- ipv4.icanhazip.com);
 geoip=$(geoiplookup $ipadd | cut -d : -f 2);
 wget -O /etc/banner "https://raw.githubusercontent.com/tjay13/TsholoVPN/master/Tools/Other/banner"
 cat > /etc/banner <<-END
-<br><font color="blue"><b>TsholoVPN</b><br></font><br>
+<br><font color="blue"><b>Thank you for using TsholoVPN</b><br></font><br>
 <br><font color="red"><b> Location Server: $geoip</b></font><br>
 END
 sed -i 's@#Banner none@Banner /etc/banner@g' /etc/ssh/sshd_config
 sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/banner"@g' /etc/default/dropbear
-
-# Activate OpenVPN Auth Script
-sed -i -e 's/\r$//' /etc/openvpn/script/auth_vpn.sh
 
 clear
 echo "INSTALLING WEBSOCKET OPENVPN PYTHON"
@@ -309,7 +594,7 @@ echo "$so1"
 
 mkdir /usr/sbin/kpn
 wget -O /usr/sbin/kpn/connection.php https://raw.githubusercontent.com/tjay13/TsholoVPN/master/Tools/Menu/connection.php &> /dev/null
-chmod -R 777 /usr/sbin/kpn/connection.php
+chmod -R 755 /usr/sbin/kpn/connection.php
 echo "* * * * * root /usr/bin/php /usr/sbin/kpn/connection.php >/dev/null 2>&1" > /etc/cron.d/connection-ssh
 echo "* * * * * root /bin/bash /usr/sbin/kpn/active.sh>/dev/null 2>&1"> /etc/cron.d/active-users
 echo "* * * * * root /bin/bash /usr/sbin/kpn/inactive.sh >/dev/null 2>&1" > /etc/cron.d/inactive-users
@@ -333,9 +618,15 @@ service crond start
 chkconfig stunnel on
 chkconfig crond on
 systemctl daemon-reload
+
 systemctl enable ws.service
 systemctl start ws.service
 systemctl restart ws.service
+
+systemctl enable wsssh.service
+systemctl start wsssh.service
+systemctl restart wsssh.service
+
 systemctl enable stunnel.service
 systemctl start stunnel.service
 systemctl restart stunnel.service
